name: gad7
description: App for tracking anxiety symptoms over time.
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.0
  sqflite: ^1.1.7
  path_provider: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Steradian
      fonts:
        - asset: assets/fonts/Steradian-Regular.otf
          weight: 300
        - asset: assets/fonts/Steradian-Medium.otf
          weight: 500
        - asset: assets/fonts/Steradian-Bold.otf
          weight: 700